### ISSUE TITLE
azure-event-hubs-java-eph on multiple hosts information

### ISSUE THREAD

**Issue by yoannbi** [Azure/azure-event-hubs-java#105]
hi, i use the azure-event-hubs libs 0.13.1 with EventHostProcessor on 3 hosts.

I receive this logs on each hosts

WARNING: host devqalogsysperf1: partition 1: EventHub client disconnected, probably another host took the partition
Apr 25, 2017 8:43:41 AM com.microsoft.azure.eventhubs.ReceivePump run
WARNING: Receive pump for partition (1) exiting after receive exception com.microsoft.azure.servicebus.ReceiverDisconnectedException: New receiver with higher epoch of '4' is created hence current receiver with epoch '3' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. TrackingId:, SystemTracker:log2:eventhub:cnm~4095|test, Timestamp:4/25/2017 8:43:40 AM, errorContext[NS: logsdbos2.servicebus.windows.net, PATH: cnm/ConsumerGroups/test/Partitions/1, REFERENCE_ID: ed362b_d4, PREFETCH_COUNT: 300, LINK_CREDIT: 1680, PREFETCH_Q_LEN: 0]

WARNING: host devqalogsysperf3: partition 15: Inner exception com.microsoft.azure.servicebus.ReceiverDisconnectedException: A receiver with a higher epoch '3' already exists. A new receiver with epoch 2 cannot be created. Make sure you are creating receiver with increasing epoch value to ensure connectivity, or ensure all old epoch receivers are closed or disconnected. TrackingId:ad5, SystemTracker:l:eventhub:cnm~32766, Timestamp:4/25/2017 8:53:17 AM Reference:02f0, TrackingId:2, SystemTracker::eventhub:cnm~32766|test, Timestamp:4/25/2017 8:53:18 AM TrackingId:, SystemTracker:gateway2, Timestamp:4/25/2017 8:53:17 AM, errorContext[NS: log.servicebus.windows.net, PATH: cnm/ConsumerGroups/test/Partitions/15, REFERENCE_ID:]
Apr 25, 2017 8:53:16 AM com.microsoft.azure.eventprocessorhost.EventProcessorHost log
WARNING: host devqalogsysperf3: partition 15: com.microsoft.azure.servicebus.ExceptionUtil.toException(ExceptionUtil.java:35)
Apr 25, 2017 8:53:16 AM com.microsoft.azure.eventprocessorhost.EventProcessorHost log
WARNING: host devqalogsysperf3: partition 15: com.microsoft.azure.servicebus.MessageReceiver.onClose(MessageReceiver.java:587)
Apr 25, 2017 8:53:16 AM com.microsoft.azure.eventprocessorhost.EventProcessorHost log
WARNING: host devqalogsysperf3: partition 15: com.microsoft.azure.servicebus.amqp.BaseLinkHandler.processOnClose(BaseLinkHandler.java:75)

SEVERE: host devqalogsysperf0: partition 1: java.lang.Thread.run(Thread.java:745)
Apr 25, 2017 9:02:31 AM com.microsoft.azure.eventprocessorhost.EventProcessorHost log
SEVERE: host devqalogsysperf0: partition 1: Ignoring out of date checkpoint with offset 262011108048/sequence number 1288750 because current persisted checkpoint has higher offset 262011110048/sequence number 1288752
Apr 25, 2017 9:02:31 AM com.microsoft.azure.eventprocessorhost.EventProcessorHost log
SEVERE: host devqalogsysperf0: partition 1: Got exception from onEvents
Apr 25, 2017 9:02:31 AM com.microsoft.azure.eventprocessorhost.EventProcessorHost log

Do you know if its ok ? or where i can fix this pbs ?

**Comment by yoannbi** [comment]
do you need more information ?

**Comment by yoannbi** [comment]
Today one server exit with this trace `Apr 28, 2017 8:14:28 AM com.microsoft.azure.eventprocessorhost.EventProcessorHos                                             t log
WARNING: host devqalogsysperf2: com.microsoft.azure.eventprocessorhost.AzureStor                                             ageCheckpointLeaseManager.lambda$getLease$7(AzureStorageCheckpointLeaseManager.j                                             ava:296)
Apr 28, 2017 8:14:28 AM com.microsoft.azure.eventprocessorhost.EventProcessorHos                                             t log
WARNING: host devqalogsysperf2: java.util.concurrent.FutureTask.run(FutureTask.j                                             ava:266)
Apr 28, 2017 8:14:28 AM com.microsoft.azure.eventprocessorhost.EventProcessorHos                                             t log
WARNING: host devqalogsysperf2: java.util.concurrent.ThreadPoolExecutor.runWorke                                             r(ThreadPoolExecutor.java:1142)
Apr 28, 2017 8:14:28 AM com.microsoft.azure.eventprocessorhost.EventProcessorHos                                             t log
WARNING: host devqalogsysperf2: java.util.concurrent.ThreadPoolExecutor$Worker.r                                             un(ThreadPoolExecutor.java:617)
Apr 28, 2017 8:14:28 AM com.microsoft.azure.eventprocessorhost.EventProcessorHos                                             t log
WARNING: host devqalogsysperf2: java.lang.Thread.run(Thread.java:745)
`

**Comment by jmakuc** [comment]
I'm getting the same error randomly from the driver version 0.14.4.

This exception is thrown and catched by the EventProcessorHost, so there is nothing we could do in the app itself.

My stack trace:

`017-09-25 19:47:54 [WARNING] eventprocessorhost.trace host dems-test.servicebus.windows.net: partition 0: EventHub client disconnected, probably another host took the partition
2017-09-25 19:47:54 [WARNING] servicebus.trace Receive pump for partition (0) exiting after receive exception com.microsoft.azure.servicebus.ReceiverDisconnectedException: New receiver with higher epoch of '177' is created hence current receiver with epoch '177' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. TrackingId:5beb3d9b00001d770050d75159c98796_G24_B26, SystemTracker:dems-test:eventhub:dems-test-eventhub~16383|$default, Timestamp:9/25/2017 10:47:55 PM, errorContext[NS: dems-test.servicebus.windows.net, PATH: dems-test-eventhub/ConsumerGroups/$Default/Partitions/0, REFERENCE_ID: 110dbd_ecc_G24_1506379653813, PREFETCH_COUNT: 300, LINK_CREDIT: 1698, PREFETCH_Q_LEN: 0]
2017-09-25 19:47:54 [WARNING] cl.bithaus.messaging.service.driver.azure.eventhub.BHMessagingServiceAzureEventHubDriver ERROR  partition dems-test-eventhub / $Default / 0: New receiver with higher epoch of '177' is created hence current receiver with epoch '177' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. TrackingId:5beb3d9b00001d770050d75159c98796_G24_B26, SystemTracker:dems-test:eventhub:dems-test-eventhub~16383|$default, Timestamp:9/25/2017 10:47:55 PM, errorContext[NS: dems-test.servicebus.windows.net, PATH: dems-test-eventhub/ConsumerGroups/$Default/Partitions/0, REFERENCE_ID: 110dbd_ecc_G24_1506379653813, PREFETCH_COUNT: 300, LINK_CREDIT: 1698, PREFETCH_Q_LEN: 0]
com.microsoft.azure.servicebus.ReceiverDisconnectedException: New receiver with higher epoch of '177' is created hence current receiver with epoch '177' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. TrackingId:5beb3d9b00001d770050d75159c98796_G24_B26, SystemTracker:dems-test:eventhub:dems-test-eventhub~16383|$default, Timestamp:9/25/2017 10:47:55 PM, errorContext[NS: dems-test.servicebus.windows.net, PATH: dems-test-eventhub/ConsumerGroups/$Default/Partitions/0, REFERENCE_ID: 110dbd_ecc_G24_1506379653813, PREFETCH_COUNT: 300, LINK_CREDIT: 1698, PREFETCH_Q_LEN: 0]
	at com.microsoft.azure.servicebus.ExceptionUtil.toException(ExceptionUtil.java:35)
	at com.microsoft.azure.servicebus.MessageReceiver.onClose(MessageReceiver.java:587)
	at com.microsoft.azure.servicebus.amqp.BaseLinkHandler.processOnClose(BaseLinkHandler.java:75)
	at com.microsoft.azure.servicebus.amqp.BaseLinkHandler.onLinkRemoteClose(BaseLinkHandler.java:46)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:309)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:276)
	at com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:381)
	at java.lang.Thread.run(Thread.java:745)
`

We see in the log that this exception happens randomly and then a new EventProcessorHost is created for each partition (2 in this case).

Any ideas?

**Comment by JamesBirdsall** [comment]
If ownership of a partition moves from one host instance to another, for whatever reason, this is expected on the old instance: the new one has started a receiver with a higher epoch, which kicks the old one off. So the real question is why the move is happening. If the old host cannot renew the lease for some reason and so some other host grabs it, that's one common reason. Another would be changing the number of host instances (starting up or shutting down a node.) Can you be more specific about "a new EventProcessorHost is created for each partition"?

**Comment by jmakuc** [comment]
Hi James

Thanks for the quick reply.

We are running only 1 instance of the consumer app and not using those
credentials in any other app.

The consumption continues with small delays because of the esceptions. We
are running tests to see if messages are beign lost.

Best
J

**Comment by JamesBirdsall** [comment]
When ownership moves, event processing starts from the last checkpoint. Reprocessing of some events is common, depending on how often you checkpoint, but you should not see any events being skipped.

**Comment by jmakuc** [comment]
We ack messages one by one upon saving them on our side.

Here are code snippets of how we are using the EPH and log output. The class where this code is, implements IEventProcessor.

```
                    this.epHost = new EventProcessorHost(
                            this.conf.getHost(),
                            this.conf.getEventHubName(), 
                            this.conf.getConsumerGroupName(),
                            connStr.toString(), 
                            this.conf.getStorageConnectionString(), 
                            this.conf.getStorageContainerName()); 

                    EventProcessorOptions options = new EventProcessorOptions();
                    options.setExceptionNotification(new ExceptionConsumer());                    
                    options.setPrefetchCount(1);

                    final BHMessagingServiceAzureEventHubDriver driver = this;
                    IEventProcessorFactory factory = (PartitionContext context) -> {
                        logger.info("New EventProcessor for " + context.getEventHubPath() + "/" + context.getPartitionId());
                        return driver;
                    };
                    this.epHost.registerEventProcessorFactory(factory);
                    logger.info("Event processor factory registered OK");

                    logger.info("Waiting for Event Processor...");
                    connectionSemaphore.acquire();

                logger.info("Start complete");

```

We launch only 1 instance and this is the output:

```
2017-09-26 13:33:44 [INFO] EventHubDriver Event processor factory registered OK
2017-09-26 13:33:44 [INFO] EventHubDriver Waiting for Event Processor...
2017-09-26 13:33:52 [INFO] EventHubDriver New EventProcessor for dems-test-eventhub/1
2017-09-26 13:33:52 [INFO] EventHubDriver New EventProcessor for dems-test-eventhub/0
2017-09-26 13:33:52 [INFO] EventHubDriver OPEN partition dems-test-eventhub / $Default / 1
2017-09-26 13:33:52 [INFO] EventHubDriver OPEN partition dems-test-eventhub / $Default / 0
2017-09-26 13:33:52 [INFO] EventHubDriver Start complete
2017-09-26 13:33:52 [INFO] Main Locking main thread.
2017-09-26 13:34:17 [WARNING] eventprocessorhost.trace host dems-test.servicebus.windows.net: partition 1: EventHub client disconnected, probably another host took the partition
2017-09-26 13:34:17 [WARNING] servicebus.trace Receive pump for partition (1) exiting after receive exception com.microsoft.azure.servicebus.ReceiverDisconnectedException: New receiver with higher epoch of '403' is created hence current receiver with epoch '402' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. TrackingId:ef3a8dc500001d76005db1dd59ca8174_G17_B27, SystemTracker:dems-test:eventhub:dems-test-eventhub~32766|$default, Timestamp:9/26/2017 4:34:18 PM, errorContext[NS: dems-test.servicebus.windows.net, PATH: dems-test-eventhub/ConsumerGroups/$Default/Partitions/1, REFERENCE_ID: 273ecc_298_G17_1506443635147, PREFETCH_COUNT: 300, LINK_CREDIT: 1698, PREFETCH_Q_LEN: 0]
2017-09-26 13:34:17 [WARNING] EventHubDriver ERROR  partition dems-test-eventhub / $Default / 1: New receiver with higher epoch of '403' is created hence current receiver with epoch '402' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. TrackingId:ef3a8dc500001d76005db1dd59ca8174_G17_B27, SystemTracker:dems-test:eventhub:dems-test-eventhub~32766|$default, Timestamp:9/26/2017 4:34:18 PM, errorContext[NS: dems-test.servicebus.windows.net, PATH: dems-test-eventhub/ConsumerGroups/$Default/Partitions/1, REFERENCE_ID: 273ecc_298_G17_1506443635147, PREFETCH_COUNT: 300, LINK_CREDIT: 1698, PREFETCH_Q_LEN: 0]
com.microsoft.azure.servicebus.ReceiverDisconnectedException: New receiver with higher epoch of '403' is created hence current receiver with epoch '402' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. TrackingId:ef3a8dc500001d76005db1dd59ca8174_G17_B27, SystemTracker:dems-test:eventhub:dems-test-eventhub~32766|$default, Timestamp:9/26/2017 4:34:18 PM, errorContext[NS: dems-test.servicebus.windows.net, PATH: dems-test-eventhub/ConsumerGroups/$Default/Partitions/1, REFERENCE_ID: 273ecc_298_G17_1506443635147, PREFETCH_COUNT: 300, LINK_CREDIT: 1698, PREFETCH_Q_LEN: 0]
	at com.microsoft.azure.servicebus.ExceptionUtil.toException(ExceptionUtil.java:35)
	at com.microsoft.azure.servicebus.MessageReceiver.onClose(MessageReceiver.java:587)
	at com.microsoft.azure.servicebus.amqp.BaseLinkHandler.processOnClose(BaseLinkHandler.java:75)
	at com.microsoft.azure.servicebus.amqp.BaseLinkHandler.onLinkRemoteClose(BaseLinkHandler.java:46)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:309)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:276)
	at com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:381)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by JamesBirdsall** [comment]
With this info, I was able to check the service-side logs and I am seeing receivers connecting from two different IP addresses. Are you sure there's only one instance running?

**Comment by jmakuc** [comment]
Hey James

Thank you very much for that info. In fact there was another process using
this credentials by mistake :(

I'm so sorry!

Thanks again for the help :)




Jonathan Makuc

*Bit**haus Software Boutique*
# --------------------------------------------------------
0x77 bithaus.cl
0x74 +56994191736
0x3F Encomenderos 236, Of 202, Las Condes, Santiago, Chile
Truth is out there
