### ISSUE TITLE
Number of thread increased a lot after partitions leave and come back on a consumer

### ISSUE THREAD

**Issue by fdubois-fa** [Azure/azure-event-hubs-java#113]
## Actual Behavior
On server environment we discovered that the load average increased continuously by step from time to time without reducing. Every other metrics were good that we made a thread dump. Then we saw lots of threads like:
```
"Thread-248" #6514 prio=5 os_prio=0 tid=0x0000000018a7d800 nid=0x1c40 runnable [0x000000002da8e000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(WindowsSelectorImpl.java:296)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(WindowsSelectorImpl.java:278)
	at sun.nio.ch.WindowsSelectorImpl.doSelect(WindowsSelectorImpl.java:159)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x0000000083454ec8> (a sun.nio.ch.Util$2)
	- locked <0x0000000083454eb8> (a java.util.Collections$UnmodifiableSet)
	- locked <0x0000000083454620> (a sun.nio.ch.WindowsSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at org.apache.qpid.proton.reactor.impl.SelectorImpl.select(SelectorImpl.java:126)
	at org.apache.qpid.proton.reactor.impl.IOHandler.handleQuiesced(IOHandler.java:57)
	at org.apache.qpid.proton.reactor.impl.IOHandler.onUnhandled(IOHandler.java:381)
	at org.apache.qpid.proton.engine.BaseHandler.onReactorQuiesced(BaseHandler.java:87)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:206)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:309)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:277)
	at com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:375)
	at java.lang.Thread.run(Thread.java:745)
```

Trying to isolate the problem, I just run consumer on my laptop, add a new consumer, and a third one. Everything looked good. Then I closed one and saw on the 2 running consumers 17 threads for polling, which looked strange to me (I expected 16 on each with 32 partitions). Then I closed the second consumer and now the first one got 113 threads. I join a thread dump.

This is not systematic. I did not find a pattern to reproduce it. The thing is that from time to time and due to partition relocation, the number of threads increase a lot and never come back to normal after. Understand the code better than me you may find a reason, side effect that can generate that.

[threaddump-eventhub.txt](https://github.com/Azure/azure-event-hubs-java/files/1014229/threaddump-eventhub.txt)

## Expected Behavior
1. I think the number of thread for polling should be equal to the number of partitions managed by the process.
2. The number of thread should not increase continuously.

## Versions  
- OS platform and version: Linux Ubuntu 14.04 LTS and Windows 7 (for my tests)
- Maven package version or commit ID: 0.14.0

**Comment by adoelger** [comment]
Same problem for me!

**Comment by SreeramGarlapati** [comment]
We addressed several issues which could have contributed to thread leak.
And then, in PR #215 - we made sure javaclient no longer new's up any thread and only uses the `Executor` provided by user.
