### ISSUE TITLE
Old epoch error when starting receiver

### ISSUE THREAD

**Issue by royyeah** [Azure/azure-event-hubs-java#328]
## Actual Behavior
1. Old epoch error when starting EventProcessorRunnable, probably because the old receiver did not shutdown gracefully.

> 2018-06-02 11:56:23,325 ERROR [pool-2-thread-5] c.m.a.e.PartitionPump - host eventhub-to-cassandra-840ef514-fba7-413e-8f52-fa89d943961b: 3: PartitionReceiver creation failed
> java.util.concurrent.CompletionException: com.microsoft.azure.eventhubs.ReceiverDisconnectedException: A receiver with a higher epoch '23' already exists. A new receiver with epoch 20 cannot be created. Make sure you are creating receiver with increasing epoch value to ensure connectivity, or ensure all old epoch receivers are closed or disconnected. TrackingId:fd7599f7-d0a9-4703-a081-8addadc46bf8_B3, SystemTracker:made-anonymous:eventhub:test~4095|cgcassandra, Timestamp:6/2/2018 11:56:22 AM Reference:2df5abb4-eb6e-4da3-ba3b-d47c5c722a9d, TrackingId:02ce29a7-c73d-4e87-8ea3-7f0a3ea57276_B3, SystemTracker:made-anonymous:eventhub:test~4095|cgcassandra, Timestamp:6/2/2018 11:56:23 AM TrackingId:34a259e08fe542d29fbc8114f5ddbdcf_G24, SystemTracker:gateway5, Timestamp:6/2/2018 11:56:23 AM, errorContext[NS: made-anonymous.servicebus.windows.net, PATH: test/ConsumerGroups/cgcassandra/Partitions/3, REFERENCE_ID: bedd2b_dcf_G24_1527940572951]
>         at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
>         at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
>         at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
>         at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
>         at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
>         at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
>         at com.microsoft.azure.eventhubs.impl.ExceptionUtil.completeExceptionally(ExceptionUtil.java:86)
>         at com.microsoft.azure.eventhubs.impl.MessageReceiver.onOpenComplete(MessageReceiver.java:305)
>         at com.microsoft.azure.eventhubs.impl.MessageReceiver.onError(MessageReceiver.java:364)
>         at com.microsoft.azure.eventhubs.impl.MessageReceiver.onClose(MessageReceiver.java:607)
>         at com.microsoft.azure.eventhubs.impl.BaseLinkHandler.processOnClose(BaseLinkHandler.java:50)
>         at com.microsoft.azure.eventhubs.impl.BaseLinkHandler.handleRemoteLinkClosed(BaseLinkHandler.java:70)
>         at com.microsoft.azure.eventhubs.impl.BaseLinkHandler.onLinkRemoteClose(BaseLinkHandler.java:36)
>         at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176)
>         at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
>         at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
>         at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
>         at com.microsoft.azure.eventhubs.impl.MessagingFactory$RunReactor.run(MessagingFactory.java:462)
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>         at java.lang.Thread.run(Thread.java:748)
> Caused by: com.microsoft.azure.eventhubs.ReceiverDisconnectedException: A receiver with a higher epoch '23' already exists. A new receiver with epoch 20 cannot be created. Make sure you are creating receiver with increasing epoch value to ensure connectivity, or ensure all old epoch receivers are closed or disconnected. TrackingId:fd7599f7-d0a9-4703-a081-8addadc46bf8_B3, SystemTracker:made-anonymous:eventhub:test~4095|cgcassandra, Timestamp:6/2/2018 11:56:22 AM Reference:2df5abb4-eb6e-4da3-ba3b-d47c5c722a9d, TrackingId:02ce29a7-c73d-4e87-8ea3-7f0a3ea57276_B3, SystemTracker:made-anonymous:eventhub:test~4095|cgcassandra, Timestamp:6/2/2018 11:56:23 AM TrackingId:34a259e08fe542d29fbc8114f5ddbdcf_G24, SystemTracker:gateway5, Timestamp:6/2/2018 11:56:23 AM, errorContext[NS: made-anonymous.servicebus.windows.net, PATH: test/ConsumerGroups/cgcassandra/Partitions/3, REFERENCE_ID: bedd2b_dcf_G24_1527940572951]
>         at com.microsoft.azure.eventhubs.impl.ExceptionUtil.toException(ExceptionUtil.java:33)
>         at com.microsoft.azure.eventhubs.impl.MessageReceiver.onClose(MessageReceiver.java:606)
>         ... 15 more

## Expected Behavior
1. No error

What does it mean and how can I solve it? I think I got it because the old receiver did not shutdown gracefully. Could this be? How can I start a new receiver when it happened?

## Versions  
- OS platform and version: Debian 8
- Maven package version or commit ID: azure-eventhubs-eph 1.0.0 (why is there no 1.0.1 for this package?) / azure-eventhubs 1.0.1

**Comment by royyeah** [comment]
My bad old receiver was still running
