### ISSUE TITLE
StorageException when use event hub processor in region chinanorth

### ISSUE THREAD

**Issue by warrenzhu25** [Azure/azure-event-hubs-java#390]
## Actual Behavior
1.  Exception thrown
```
[pool-10-thread-6] ERROR com.microsoft.azure.eventprocessorhost.PartitionManager - host ZHONZH-ef4ea14f-a482-4310-96eb-f08a892d794f: Exception while initializing stores (Creating Lease Store), not starting partition manager
com.microsoft.azure.storage.StorageException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
	at com.microsoft.azure.storage.StorageException.translateFromHttpStatus(StorageException.java:175)
	at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:94)
	at com.microsoft.azure.storage.core.StorageRequest.materializeException(StorageRequest.java:315)
	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:175)
	at com.microsoft.azure.storage.blob.CloudBlobContainer.exists(CloudBlobContainer.java:769)
	at com.microsoft.azure.storage.blob.CloudBlobContainer.createIfNotExists(CloudBlobContainer.java:379)
	at com.microsoft.azure.storage.blob.CloudBlobContainer.createIfNotExists(CloudBlobContainer.java:348)
	at com.microsoft.azure.eventprocessorhost.AzureStorageCheckpointLeaseManager.lambda$createLeaseStoreIfNotExistsInternal$8(AzureStorageCheckpointLeaseManager.java:328)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
``` 

## Expected Behavior
1. No exception

## Versions  
- OS platform and version: Windows 10
- Maven package version or commit ID: azure-eventhubs-eph 1.0.0

**Comment by JamesBirdsall** [comment]
Is your Storage connection string OK? EPH just passes all the Storage connection/auth stuff through to the Storage client without modifying it.

**Comment by warrenzhu25** [comment]
Fixed this after changing `EndpointSuffix` into `core.chinacloudapi.cn`
