### ISSUE TITLE
Integration with Storage SDK v10?

### ISSUE THREAD

**Issue by marcioos** [Azure/azure-event-hubs-java#429]
## Actual Behavior
1. I'm working on a project where Blob Storage and Event Hubs are both first class citizens, but right now I can't update to the latest major version of the Storage Java SDK (v10) because it conflicts with the version required by the `azure-eventhubs-eph` module. I get the following exception:
```Caused by:
        java.lang.SecurityException: class "com.microsoft.azure.storage.blob.BlobListingDetails"'s signer information does not match signer information of other classes in the same package
            at java.lang.ClassLoader.checkCerts(ClassLoader.java:898)
            at java.lang.ClassLoader.preDefineClass(ClassLoader.java:668)
            at java.lang.ClassLoader.defineClass(ClassLoader.java:761)
            at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
            at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
            at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
            at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
            at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
            at java.security.AccessController.doPrivileged(Native Method)
            at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
            at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
            at com.microsoft.azure.eventprocessorhost.EventProcessorHost.<init>(EventProcessorHost.java:152)
            at com.microsoft.azure.eventprocessorhost.EventProcessorHost.<init>(EventProcessorHost.java:98)
```
Is there a plan to make `azure-eventhubs-eph` use the newest Storage SDK?

## Expected Behavior
1. The latest versions of `azure-eventhubs-eph` and `azure-storage-blob` can coexist in the same project.

**Comment by JamesBirdsall** [comment]
We are aware of it as a work item but it is not scheduled yet, because until now we've had no demand. The readme for the new Storage client makes it clear that this isn't just a matter of changing the pom, so it's going to require reworking the code and a substantial test cycle.

**Comment by marcioos** [comment]
Thanks for the reply.

I've just worked on migrating from 8.0.0 to v10 and it really isn't that
complicated.

Looking at your usage of it, I'd consider that work item a low hanging
fruit in the next planning meeting. Besides, I think it's something that
has to be done anyway, to avoid sticking with discontinued SDK dependency.

**Comment by JamesBirdsall** [comment]
Thanks for the tip that it's not as big a change as the readme makes it sound like. We will take that into account when planning!

**Comment by marcioos** [comment]
Hey @JamesBirdsall, I'll have to take that back. We ran into several Netty errors and warnings while testing the new Storage SDK more extensively. We are rolling back to `8.1.0` as v10 seems unstable and not as mature.

**Comment by JamesBirdsall** [comment]
Thanks for the update! We will revisit moving to v10 after it's had some time to mature.
